### ISSUE TITLE
[discovery] discovery-client.js

### ISSUE THREAD

**Issue by nganesan9** [watson-developer-cloud/discovery-nodejs-static#8]
discovery-client.js needs "use strict" in the first line for successful compilation. 
"npm start" failed at my end (localhost) for the original code. This was the error:
`Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`
It got resolved when I added "use strict" in the first line of that file. Is it just me or are other having an issue too?

**Comment by kognate** [comment]
What version of node are you using?  

This error doesn't show up in v6.2.1

**Comment by nganesan9** [comment]
Thanks for pointing that out. Mine was 4.2.4.

**Comment by kognate** [comment]
Can you upgrade to node 6 or are you locked on 4?

**Comment by nganesan9** [comment]
Was able to upgrade to v7.4.0
